# Generated by Django 5.1.5 on 2026-07-25 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchapp_one', '0002_customerdetails_gstin'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTInvoiceMaster',
            fields=[
                ('S_No', models.IntegerField(null=True)),
                ('Invoice_No', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Date', models.DateField(null=True)),
                ('Customer_Id', models.CharField(max_length=20, null=True)),
                ('Agent_Id', models.CharField(max_length=20, null=True)),
                ('Customer_Name', models.CharField(max_length=50, null=True)),
                ('P_O_No', models.CharField(max_length=50, null=True)),
                ('Tax_Type', models.CharField(max_length=10, null=True)),
                ('Total_Amount', models.FloatField(default=0)),
                ('SGST_Amount', models.FloatField(default=0)),
                ('CGST_Amount', models.FloatField(default=0)),
                ('IGST_Amount', models.FloatField(default=0)),
                ('Grand_Total', models.FloatField(default=0)),
                ('Status', models.IntegerField(default=1)),
                ('Added_By', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GSTInvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(null=True)),
                ('HSN_Code', models.CharField(max_length=50, null=True)),
                ('Qty', models.FloatField(default=0)),
                ('Fitting', models.CharField(blank=True, max_length=50, null=True)),
                ('Rate', models.FloatField(default=0)),
                ('Amount', models.FloatField(default=0)),
                ('Invoice_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branchapp_one.gstinvoicemaster')),
            ],
        ),
    ]
