# Generated by Django 5.1.5 on 2026-07-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branchapp_one', '0003_gstinvoicemaster_gstinvoicedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gstinvoicedetails',
            name='Fitting',
        ),
    ]
