# Generated by Django 5.1.5 on 2025-03-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='Agent_Id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='Customer_Id',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='Final_Total_Cost',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='Final_Total_Cost_With_Gst',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='GST',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='HSN_Code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='Item_Id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='Size',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='Total_Cost',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='Total_Cost_With_Gst',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='Type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='billingmaster',
            name='Agent_Id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='billingmaster',
            name='Bill_Id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='billingmaster',
            name='Customer_Id',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='billingmaster',
            name='Type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='categoriesmaster',
            name='Categories_Id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoriesmaster',
            name='Size',
            field=models.CharField(default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='costmaster',
            name='Cost_Id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='costmaster',
            name='Size',
            field=models.CharField(default='None', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Agent_Id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Customer_Id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='Type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='Agent_Id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customermaster',
            name='Customer_Id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inwardmaster',
            name='Batch_Id',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='inwardmaster',
            name='Batch_No',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='inwardmaster',
            name='Inward_Id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inwardmaster',
            name='Material_Id',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='inwardmaster',
            name='Vendor_GST',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='materialmaster',
            name='Material_Id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='GST',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='HSN_Code',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='Product_Id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotemaster',
            name='Customer_Id',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='quotemaster',
            name='Quote_Id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotemaster',
            name='Type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
