# Generated by Django 5.1.5 on 2025-03-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0002_alter_billingdetails_agent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutwardMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Outward_Id', models.CharField(max_length=15)),
                ('Inward_Id', models.CharField(max_length=15, null=True)),
                ('Date', models.DateField(null=True)),
                ('Material_Id', models.CharField(max_length=15)),
                ('Material_Name', models.CharField(max_length=15)),
                ('Used_By', models.CharField(max_length=15)),
                ('Outward_Quantity', models.IntegerField()),
                ('Batch_Id', models.CharField(max_length=15)),
                ('Batch_No', models.CharField(max_length=50)),
                ('Additional_Info', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='inwardmaster',
            name='Material_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='billingmaster',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='inwardmaster',
            name='Batch_No',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='materialmaster',
            name='Material_Size_In_Feet',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='materialmaster',
            name='Material_Size_In_Meters',
            field=models.FloatField(),
        ),
    ]
