# Generated by Django 5.1.5 on 2025-03-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0003_outwardmaster_inwardmaster_material_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costmaster',
            name='Production_Cost',
        ),
        migrations.RemoveField(
            model_name='costmaster',
            name='Profit_Percent',
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='Added_By',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
