# Generated by Django 5.1.5 on 2025-04-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0004_remove_costmaster_production_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmaster',
            name='S_No',
            field=models.IntegerField(null=True),
        ),
    ]
