# Generated by Django 5.1.5 on 2025-05-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0005_billingmaster_s_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pan',
        ),
    ]
