# Generated by Django 5.1.5 on 2025-05-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0007_billingdetails_additional_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotedetails',
            name='Custom_Product',
        ),
        migrations.AddField(
            model_name='quotedetails',
            name='Additional_Charges',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='quotemaster',
            name='S_No',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quotedetails',
            name='Agent_Id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='quotedetails',
            name='Customer_Id',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='quotedetails',
            name='Final_Total_Cost',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='quotedetails',
            name='Final_Total_Cost_With_Gst',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='quotedetails',
            name='GST',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='quotedetails',
            name='HSN_Code',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='quotedetails',
            name='Item_Id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='quotedetails',
            name='Modified_Cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quotedetails',
            name='Size',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='quotedetails',
            name='Total_Cost',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='quotedetails',
            name='Total_Cost_With_Gst',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='quotedetails',
            name='Type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='quotemaster',
            name='Agent_Id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
