# Generated by Django 5.1.5 on 2025-06-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0009_cash_book_master_expense_category_cash_book_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Office_Branch',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
