# Generated by Django 5.1.5 on 2026-07-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0010_employee_office_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='GSTIN',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
