# Generated by Django 6.0.5 on 2026-07-28 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0014_gstquotationmaster_gstquotationdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallanMaster',
            fields=[
                ('S_No', models.IntegerField(null=True)),
                ('Challan_No', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Date', models.DateField(null=True)),
                ('Customer_Id', models.CharField(max_length=20, null=True)),
                ('Agent_Id', models.CharField(max_length=20, null=True)),
                ('Customer_Name', models.CharField(max_length=50, null=True)),
                ('Mode_of_Despatch', models.CharField(blank=True, max_length=100, null=True)),
                ('Veh_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Date_and_Time_of_Supply', models.CharField(blank=True, max_length=100, null=True)),
                ('Place_of_Supply', models.CharField(blank=True, max_length=100, null=True)),
                ('Total_Qty', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=1)),
                ('Added_By', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(null=True)),
                ('Size', models.CharField(blank=True, max_length=50, null=True)),
                ('Qty', models.IntegerField(default=0)),
                ('Material', models.CharField(blank=True, max_length=50, null=True)),
                ('Rate', models.FloatField(default=0)),
                ('Value', models.FloatField(default=0)),
                ('Challan_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssdapp.deliverychallanmaster')),
            ],
        ),
    ]
