# Generated by Django 6.0.5 on 2026-09-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssdapp', '0015_deliverychallanmaster_deliverychallandetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstquotationmaster',
            name='Message_Topic',
            field=models.CharField(default='Branding works', max_length=255, null=True),
        ),
    ]
